[platformio]
default_envs = board_a

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

[env:board_a]
lib_ldf_mode = deep
build_src_filter =
    +<board_a/>
    -<board_b/>
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9
    fastled/FastLED @ 3.6.0
    madhephaestus/ESP32Servo @ ^1.1.2
    seeed-studio/Grove Gesture

[env:board_b]
build_src_filter =
    +<board_b/>
    -<board_a/>
